# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a87b37a0ebe3b720d0ec0e101c5ed249ab338b681c3dcf516383c38c00d283dc2be154dbaed23c381676ba2ac3a8b24d6ae38e770446c9a9e26f7b37b59e999

test:
  secret_key_base: 2c73f40fd1c33b2c99da4693731fe6e92c4a63b95f63b1bb206c1e96a0dde3dfbb89421b342ac21225edf962252247428bcfa90b26804edc01bd8a24879c52b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
